In [1]:
import time 
import RidgeDetection

path = '/media/linsel/3931-6632/data/phd stone tools/Blades_Bladelets_PLY/annotated/coloured/selected/'

name = '773'

# filename, quality_index = path + name + ".ply", 3
 
RidgeDetection.ridgedetection (path,name)

Time writing label txt file: 0.07221187600225676
Time writing label txt file: 0.059705689003749285
103.35085439682007


In [103]:
from scipy.spatial import distance

def closest_neighbours(points,k):

    D = distance.squareform(distance.pdist(points))
    print(np.round(D, 1))  # Rounding to fit the array on screen

    closest = np.argsort(D, axis=1)
    print(closest)

    k = 2  # For each point, find the 3 closest points
    print(closest[:, 1:k+1])
    
    return closest[:, 1:k+1]

In [28]:
import pymeshlab
import numpy as np
import pandas as pd

filename = path + name + ".ply"

ms = pymeshlab.MeshSet()
ms.load_new_mesh(filename)
faces = ms.current_mesh().face_matrix().tolist()
vertices = ms.current_mesh().vertex_matrix().tolist()

df_ridge = pd.read_csv(path + name + '_ridge.txt',skiprows=5,header=None,sep=' ')
df_ridge_info = pd.read_csv(path + name + '_ridge_info.txt',skiprows=5,header=None,sep=' ')
df_ridge_info [df_ridge[1] == 2]

points = pd.DataFrame(vertices)[df_ridge[1] == 2]

[[ 0.   0.1  0.3 ... 70.3 70.3 70.2]
 [ 0.1  0.   0.2 ... 70.3 70.3 70.3]
 [ 0.3  0.2  0.  ... 70.4 70.4 70.4]
 ...
 [70.3 70.3 70.4 ...  0.   0.   0.1]
 [70.3 70.3 70.4 ...  0.   0.   0.1]
 [70.2 70.3 70.4 ...  0.1  0.1  0. ]]
[[    0   564     1 ...   166   345   165]
 [    1     0   560 ...   166   345   165]
 [    2  1664  1674 ...   166   345   165]
 ...
 [10262 10263 10259 ...  1611  1614  1613]
 [10263 10262 10264 ...  1611  1614  1613]
 [10264 10263 10262 ...  1611  1614  1613]]
[[  564     1]
 [    0   560]
 [ 1664  1674]
 ...
 [10263 10259]
 [10262 10264]
 [10263 10262]]


In [75]:
ridge_point = []
cross_ridge = []

for n,point in enumerate(df_ridge_info[1]): 
    if len(point.split(',')) == 2:
        ridge_point.append([n,2])
    elif len(point.split(',')) > 2:
        ridge_point.append([n,1])
    else:
        ridge_point.append([n,0])


In [76]:
pd.DataFrame (ridge_point) [pd.DataFrame (ridge_point)[1] == 2]

0  1
33          33  2
34          34  2
37          37  2
56          56  2
57          57  2
...        ... ..
199946  199946  2
199954  199954  2
199968  199968  2
199979  199979  2
199986  199986  2

[9759 rows x 2 columns]

In [95]:
points = pd.DataFrame(vertices) [pd.DataFrame (ridge_point)[1] == 2]
# df_filter = df_ridge_info[df_ridge == '2']
#df_ridge_info[1].str.split(',',expand=True)
from scipy.spatial import distance
D = distance.squareform(distance.pdist(points))
#print(np.round(D, 1))  # Rounding to fit the array on screen

closest = np.argsort(D, axis=1)
#print(closest)

k = 2  # For each point, find the 3 closest points
neigbor = (closest[:, :k+1])

In [118]:
ridge_line = pd.DataFrame(vertices)[pd.DataFrame (ridge_point)[1] == 2]
ridge_line_neighbours = pd.DataFrame(closest_neighbours(ridge_line,2),index=list(ridge_line.index)).reindex_like(ridge_line)

[[ 0.   0.1  0.3 ... 70.3 70.3 70.2]
 [ 0.1  0.   0.2 ... 70.3 70.3 70.3]
 [ 0.3  0.2  0.  ... 70.4 70.4 70.4]
 ...
 [70.3 70.3 70.4 ...  0.   0.   0.1]
 [70.3 70.3 70.4 ...  0.   0.   0.1]
 [70.2 70.3 70.4 ...  0.1  0.1  0. ]]
[[   0  521    1 ...  316  159  309]
 [   1    0  517 ...  316  159  309]
 [   2 1569 1576 ...  316  159  309]
 ...
 [9756 9757 9753 ... 1494 1521 1523]
 [9757 9756 9758 ... 1494 1521 1523]
 [9758 9757 9756 ... 1494 1521 1523]]
[[ 521    1]
 [   0  517]
 [1569 1576]
 ...
 [9757 9753]
 [9756 9758]
 [9757 9756]]


In [135]:
ridge_line_neighbours[pd.DataFrame (ridge_point)[1] == 2]

/tmp/ipykernel_149785/3287874005.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ridge_line_neighbours[pd.DataFrame (ridge_point)[1] == 2]


0     1
33       521     1
34         0   517
37      1569  1576
56       561     4
57         3   565
...      ...   ...
199946  9752  9755
199954  9753  9754
199968  9757  9753
199979  9756  9758
199986  9757  9756

[9759 rows x 2 columns]

In [161]:
for i in np.unique(df_ridge_info[1][pd.DataFrame (ridge_point)[1] == 2]):
#     print(i)
#     print(df_ridge_info [df_ridge_info[1] == i])
#     print(points [df_ridge_info[1] == i])
#     print(ridge_line_neighbours[df_ridge_info[1] == i])
#     print (ridge_line_neighbours[df_ridge_info[1] == i].value_counts())
    
    print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])

/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info

218     3.0
328     3.0
329     NaN
1127    NaN
1130    NaN
       ... 
9269    3.0
9275    NaN
9278    NaN
9280    4.0
9281    2.0
Length: 189, dtype: float64
180     2.0
181     NaN
509     4.0
512     NaN
514     NaN
       ... 
8834    NaN
9619    NaN
9620    NaN
9622    NaN
9624    2.0
Length: 131, dtype: float64
31      3.0
32      NaN
36      NaN
37      3.0
498     NaN
       ... 
3322    NaN
3323    3.0
3324    NaN
3325    NaN
3330    2.0
Length: 103, dtype: float64
27      NaN
30      NaN
33      2.0
34      NaN
43      4.0
       ... 
9413    NaN
9679    NaN
9680    NaN
9681    NaN
9682    2.0
Length: 128, dtype: float64
3572   NaN
3581   NaN
3616   NaN
8208   NaN
dtype: float64
215     NaN
326     NaN
380     NaN
1742    NaN
1743    2.0
       ... 
9491    2.0
9492    4.0
9493    NaN
9494    3.0
9525    2.0
Length: 205, dtype: float64
48      2.0
49      NaN
85      3.0
1936    NaN
1937    NaN
       ... 
5660    NaN
5661    3.0
5662    NaN
5663    NaN
5664    NaN
Length: 9

/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info

78      NaN
79      3.0
152     4.0
153     2.0
2219    NaN
       ... 
5054    NaN
5666    NaN
5667    2.0
5669    NaN
5670    3.0
Length: 61, dtype: float64
2128    2.0
2133    NaN
2164    NaN
2165    4.0
2166    2.0
2168    NaN
2173    NaN
2174    NaN
2175    3.0
2176    NaN
3601    NaN
3603    NaN
3607    NaN
3611    3.0
3613    NaN
3618    NaN
3619    NaN
3621    NaN
4504    NaN
4512    NaN
4514    3.0
4516    2.0
4517    4.0
4519    NaN
4524    NaN
4525    NaN
4527    NaN
4529    4.0
4530    NaN
4533    NaN
4535    2.0
4867    NaN
4868    NaN
4884    NaN
4885    2.0
4886    NaN
4887    NaN
4888    3.0
4889    NaN
4891    NaN
4892    5.0
4901    NaN
5495    NaN
5504    NaN
5508    NaN
5509    5.0
5510    NaN
5512    NaN
5517    3.0
5519    2.0
5521    NaN
5526    NaN
5788    NaN
dtype: float64
62      NaN
63      2.0
64      2.0
65      3.0
66      NaN
       ... 
5820    NaN
5821    4.0
5822    3.0
5824    NaN
5831    NaN
Length: 65, dtype: float64
133     NaN
136     2.0
2270   

/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info

6137   NaN
6146   NaN
8338   NaN
dtype: float64
2805    NaN
2806    NaN
2808    3.0
2852    3.0
5951    NaN
5966    NaN
5997    NaN
5999    3.0
6001    3.0
6010    NaN
6222    NaN
8390    3.0
8404    NaN
8784    NaN
8818    NaN
8825    3.0
8827    3.0
8829    NaN
8836    2.0
8838    2.0
8844    2.0
8846    2.0
8847    4.0
8849    2.0
8852    3.0
8858    NaN
dtype: float64
252     NaN
253     4.0
254     NaN
5953    NaN
5957    3.0
5965    NaN
5966    NaN
5967    NaN
5968    3.0
5970    NaN
5971    NaN
6148    NaN
6150    NaN
8341    4.0
8342    NaN
8343    NaN
8349    NaN
8351    3.0
8353    2.0
8359    NaN
8763    NaN
8764    3.0
8765    2.0
8766    2.0
8767    NaN
8769    NaN
8770    3.0
8773    NaN
8884    2.0
8886    2.0
8889    2.0
dtype: float64
283     NaN
299     NaN
357     NaN
358     4.0
987     NaN
       ... 
9714    4.0
9716    NaN
9722    NaN
9723    3.0
9725    NaN
Length: 142, dtype: float64
3692    NaN
3701    NaN
8419    NaN
9637    NaN
9648    NaN
9649    2.0
dtype:

/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info

124    NaN
1346   NaN
3456   NaN
7122   NaN
7125   NaN
7149   NaN
8653   NaN
8665   NaN
8809   NaN
dtype: float64
124     NaN
475     NaN
490     NaN
513     3.0
518     5.0
       ... 
8332    NaN
8485    5.0
8502    NaN
8508    3.0
8522    NaN
Length: 69, dtype: float64
215     3.0
251     NaN
355     NaN
360     2.0
361     4.0
       ... 
9416    4.0
9417    NaN
9420    2.0
9426    3.0
9429    2.0
Length: 181, dtype: float64
6978   NaN
9106   NaN
dtype: float64
6985   NaN
9111   NaN
dtype: float64
3287    NaN
4385    NaN
4386    2.0
4387    NaN
4389    2.0
4390    NaN
4391    NaN
5402    NaN
dtype: float64
2093    NaN
2101    NaN
2102    3.0
2104    NaN
2107    2.0
2108    3.0
2109    NaN
2110    3.0
2111    3.0
2112    NaN
2116    2.0
3470    2.0
3477    NaN
3481    2.0
3483    NaN
3485    2.0
3492    NaN
3540    3.0
4465    NaN
4466    2.0
4738    NaN
4739    NaN
4838    2.0
5480    2.0
5481    2.0
dtype: float64
1828    2.0
1829    NaN
1833    NaN
1856    2.0
1857    3.0
1865   

/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info

495   NaN
496   NaN
dtype: float64
0       3.0
1       3.0
510     NaN
511     NaN
515     NaN
517     NaN
521     NaN
558     2.0
560     NaN
598     NaN
600     2.0
602     NaN
682     4.0
684     3.0
685     5.0
687     NaN
690     NaN
890     2.0
897     NaN
901     NaN
903     NaN
904     NaN
917     3.0
1114    NaN
1115    2.0
1118    2.0
1290    NaN
1291    3.0
1292    NaN
1487    NaN
1488    NaN
1489    4.0
1490    NaN
1491    NaN
1492    4.0
1493    3.0
1494    NaN
1495    NaN
1496    3.0
1497    2.0
1498    2.0
1500    NaN
1501    NaN
1502    3.0
1503    3.0
1504    NaN
1505    NaN
1508    NaN
1511    NaN
1512    3.0
1519    NaN
1521    2.0
1523    NaN
1552    3.0
1569    NaN
1570    NaN
1571    NaN
dtype: float64
11      NaN
12      NaN
13      4.0
22      NaN
23      3.0
       ... 
4212    3.0
4214    NaN
4215    NaN
4216    NaN
4217    NaN
Length: 91, dtype: float64
606     NaN
607     NaN
608     3.0
609     3.0
617     NaN
619     NaN
620     NaN
621     NaN
625     NaN

/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info

4337    NaN
4722    3.0
4733    NaN
4780    NaN
7430    3.0
7433    NaN
7440    3.0
7447    NaN
7641    NaN
dtype: float64
3995    NaN
3996    2.0
3999    NaN
4475    3.0
4476    3.0
4485    3.0
4487    4.0
4488    NaN
4493    3.0
4496    3.0
5013    NaN
5016    NaN
5017    3.0
dtype: float64
50      2.0
261     NaN
262     NaN
264     3.0
273     NaN
       ... 
9738    NaN
9739    NaN
9742    NaN
9744    NaN
9745    3.0
Length: 844, dtype: float64
91      NaN
123     NaN
1600    NaN
1602    NaN
1603    NaN
1604    NaN
1631    NaN
1986    NaN
1997    NaN
2095    NaN
2103    NaN
2105    NaN
2347    NaN
2809    NaN
3205    NaN
3220    NaN
3285    NaN
3296    NaN
3456    NaN
3482    3.0
3488    3.0
3496    NaN
3511    NaN
3605    NaN
3635    NaN
4326    NaN
4327    NaN
4489    NaN
4497    NaN
4703    NaN
5292    NaN
5308    NaN
5328    NaN
5423    NaN
5431    NaN
5545    NaN
5956    NaN
6489    NaN
6803    NaN
7149    NaN
7151    NaN
7153    NaN
7186    NaN
8653    NaN
8848    NaN
8912  

/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info

182     NaN
248     NaN
249     2.0
289     NaN
290     2.0
       ... 
9302    NaN
9303    2.0
9305    NaN
9306    3.0
9307    NaN
Length: 102, dtype: float64
508   NaN
539   NaN
905   NaN
907   NaN
dtype: float64
2140    3.0
2147    NaN
2148    3.0
2149    4.0
2150    NaN
2153    3.0
2154    3.0
2160    3.0
2169    NaN
2170    NaN
2171    NaN
2172    NaN
3248    NaN
3261    3.0
3262    2.0
3263    NaN
3264    2.0
3266    NaN
3270    NaN
3271    NaN
3820    NaN
3821    NaN
3823    2.0
3827    NaN
3828    3.0
3830    NaN
3835    NaN
4367    NaN
4369    3.0
4370    NaN
4384    3.0
4388    3.0
4393    2.0
4395    3.0
4398    2.0
4752    NaN
4755    2.0
4757    3.0
4759    2.0
4763    NaN
4765    2.0
4766    3.0
4770    NaN
4774    NaN
5399    2.0
5408    NaN
5631    3.0
5633    NaN
5634    NaN
5641    NaN
5643    NaN
dtype: float64
2743   NaN
2744   NaN
3820   NaN
3821   NaN
3823   NaN
3827   NaN
3830   NaN
dtype: float64
1254    NaN
1259    2.0
1266    NaN
1267    3.0
1273    3.0
      

/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info

541     NaN
551     NaN
4745    NaN
4760    NaN
7345    2.0
7346    NaN
7347    NaN
dtype: float64
53      NaN
54      NaN
118     NaN
119     NaN
144     3.0
       ... 
5943    2.0
5944    3.0
5985    NaN
5986    NaN
5987    2.0
Length: 147, dtype: float64
19      2.0
25      2.0
35      3.0
42      NaN
46      3.0
       ... 
9370    3.0
9379    2.0
9669    2.0
9674    NaN
9675    NaN
Length: 383, dtype: float64
24      2.0
26      2.0
115     NaN
178     NaN
179     NaN
       ... 
9657    2.0
9666    NaN
9670    4.0
9702    NaN
9746    NaN
Length: 234, dtype: float64
1592    NaN
1593    NaN
1600    NaN
1658    NaN
1678    NaN
1681    NaN
2103    NaN
2278    2.0
2279    NaN
2372    NaN
2442    NaN
2798    NaN
3471    NaN
4484    NaN
4492    NaN
5034    NaN
5423    NaN
5545    NaN
5561    NaN
5632    NaN
5636    NaN
dtype: float64
4705   NaN
4706   NaN
dtype: float64
309    NaN
316    NaN
6601   NaN
6613   NaN
7343   NaN
7345   NaN
7540   NaN
7543   NaN
9111   NaN
9112   NaN
dtype: 

/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[0] + ridge_line_neighbours[df_ridge_info[1] == i].apply(pd.Series.value_counts)[1])
/tmp/ipykernel_149785/442295086.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(ridge_line_neighbours[df_ridge_info

In [3]:
ms = pymeshlab.MeshSet()

ms.load_new_mesh(filename)
faces = ms.current_mesh().face_matrix().tolist()
vertices = ms.current_mesh().vertex_matrix().tolist()

faces = np.array(faces)

np.stack((faces [:,0],faces [:,1]), axis=1),np.stack((faces [:,1],faces [:,2]), axis=1),np.stack((faces [:,0],faces [:,2]), axis=1),
np.stack((faces [:,1],faces [:,0]), axis=1),np.stack((faces [:,2],faces [:,1]), axis=1),np.stack((faces [:,2],faces [:,0]), axis=1)

data = np.concatenate((np.stack((faces [:,0],faces [:,1]), axis=1),np.stack((faces [:,1],faces [:,2]), axis=1),
                       np.stack((faces [:,0],faces [:,2]), axis=1),np.stack((faces [:,1],faces [:,0]), axis=1),
                       np.stack((faces [:,2],faces [:,1]), axis=1),np.stack((faces [:,2],faces [:,0]), axis=1)), 
                       axis=0)

In [6]:
df_dict = {}

labelname = path + name + ".txt"
df_labels = pd.read_csv(labelname,skiprows=5,header=None)

In [79]:
label_list =  []

for pid,label in enumerate(df_labels[0]):
    label_list.append(label.split(' '))

df_label = pd.DataFrame (label_list,columns=['a','b'])

a   b
0            2   1
1            3   1
2            4   1
3            6   1
4            7   1
...        ...  ..
199997   63973  30
199998  121834  30
199999   86510  30
200000   37362  30
200001   11255  30

[200002 rows x 2 columns]

In [11]:
df = pd.DataFrame(data)

columns_titles = [1,0]
df_2 = df.reindex(columns=columns_titles)

df = df.append(df_2)

df = df.drop_duplicates()

/tmp/ipykernel_7793/145764601.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df_2)


In [82]:
df_label_dict = {}

time_begin = time.time()

for key,v in enumerate(vertices):
    df_dict[key] = list(df[df[0] == key][1])
    
#     if key % 10000 == 0 and key != 0:
#         print(len(vertices)/key*(time.time()-time_begin)/60)
#         print(time.time()-time_begin)

1.5562401468253135
4.668726921081543
1.6053432223721344
9.63201379776001
1.6498751587547198
14.84878134727478
1.7322688871773084
20.787070751190186
1.7470206279651324
26.205100774765015
1.734176400585307
31.21491527557373
1.727466975442909
36.27649712562561
1.729804826390147
41.51495432853699
1.7275925690466385
46.64458703994751
1.7260960969115098
51.78242087364197
1.7224319705764453
56.83975100517273
1.7192453341190683
61.89226269721985
1.7283146816145456
67.40365171432495
1.7227956729828746
72.35674548149109
1.7187379041074646
77.34248471260071
1.7162069536567728
82.3771619796753
1.71375480748976
87.40067028999329
1.7137829928472748
92.54340720176697
1.7132323075796427
97.65331840515137
1.7121141061510246
102.72587513923645


In [122]:
ridge_key = []
time_begin = time.time()

df_label_dict = dict(zip(df_label.a, df_label.b))

for key,v in enumerate(vertices):
    value = []

    for v in df_dict[key]:
#         print(df_label_dict [str(key)])
        value.append(df_label_dict [str(v)])#list(df_label[df_label[0] == str(key)][1])[0])
#         print(value)
    
    key_label = df_label_dict [str(key)] # str(list(df_label[df_label[0] == str(key)][1])[0])

    value = value + [key_label]

    if len(np.unique(value)) > 1:        
        ridge_key.append([key,2])    
    else:        
        ridge_key.append([key,1])
    
#     print(key)
#     df_dict[key] = value
#     print(value)
    if key % 10000 == 0 and key != 0:
        print(len(vertices)/key*(time.time()-time_begin)/60)
        print(time.time()-time_begin)

    
ridge_key

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0.04

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0.03922052661856015
0.9412939548492432
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0.03848895526731715
1.9629318714141846
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0.038538426

[[0, 1],
 [1, 1],
 [2, 1],
 [3, 1],
 [4, 1],
 [5, 1],
 [6, 1],
 [7, 1],
 [8, 1],
 [9, 1],
 [10, 1],
 [11, 1],
 [12, 1],
 [13, 1],
 [14, 1],
 [15, 1],
 [16, 1],
 [17, 1],
 [18, 1],
 [19, 1],
 [20, 1],
 [21, 1],
 [22, 1],
 [23, 1],
 [24, 1],
 [25, 1],
 [26, 1],
 [27, 1],
 [28, 1],
 [29, 1],
 [30, 1],
 [31, 1],
 [32, 1],
 [33, 2],
 [34, 2],
 [35, 1],
 [36, 1],
 [37, 2],
 [38, 1],
 [39, 1],
 [40, 1],
 [41, 1],
 [42, 1],
 [43, 1],
 [44, 1],
 [45, 1],
 [46, 1],
 [47, 1],
 [48, 1],
 [49, 1],
 [50, 1],
 [51, 1],
 [52, 1],
 [53, 1],
 [54, 1],
 [55, 1],
 [56, 2],
 [57, 2],
 [58, 1],
 [59, 1],
 [60, 1],
 [61, 1],
 [62, 1],
 [63, 1],
 [64, 1],
 [65, 1],
 [66, 1],
 [67, 1],
 [68, 1],
 [69, 1],
 [70, 1],
 [71, 1],
 [72, 1],
 [73, 2],
 [74, 1],
 [75, 1],
 [76, 2],
 [77, 2],
 [78, 1],
 [79, 1],
 [80, 1],
 [81, 1],
 [82, 1],
 [83, 1],
 [84, 1],
 [85, 1],
 [86, 1],
 [87, 1],
 [88, 1],
 [89, 1],
 [90, 1],
 [91, 1],
 [92, 2],
 [93, 1],
 [94, 1],
 [95, 1],
 [96, 2],
 [97, 1],
 [98, 2],
 [99, 1],
 [100, 1],

In [123]:
import python_libs.write_labels_txt as jan

C_exp = dict(ridge_key)

jan.write_labels_txt_file (C_exp,path + name + '_ridge')

# pd.DataFrame(ridge_key)[pd.DataFrame(ridge_key)[1] == 1]

Time writing label txt file: 0.062054529998931685
