In [239]:
import pandas as pd
import numpy as np

In [240]:
path = '/media/linsel/3931-6632/data/phd stone tools/Blades_Bladelets_PLY/annotated/coloured/selected/'
path = '/home/linsel/Documents/PhD/Data/Fumane/cleaned/'
name = '31' #'104_GMCF'#"31.comp.1"

filename,quality_index = path + name + '_GMCF_transmat.txt',3



In [233]:
df = pd.read_csv(filename,delimiter='###',header=None)[0]
df_out = pd.DataFrame(columns=['A', 'B', 'C', 'D'])
for row in df:
    if row[0] != "#":
        a_series = pd.Series(row.split(' '), index = df_out.columns)
        df_out = df_out.append(a_series, ignore_index=True)


/tmp/ipykernel_1469710/362081310.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv(filename,delimiter='###',header=None)[0]
/tmp/ipykernel_1469710/362081310.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_out = df_out.append(a_series, ignore_index=True)
/tmp/ipykernel_1469710/362081310.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_out = df_out.append(a_series, ignore_index=True)
/tmp/ipykernel_1469710/362081310.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_out = df_out.append(a_series, ign

In [237]:
df = pd.read_csv(filename,delimiter='###',header=None,engine='python')[0]
np_out = np.empty((0,4), float)
for row in df:
    if row[0] != "#":
        if ',' in row:
            row = row.replace(',','.')
        data = np.array([float(x) for x in row.split(' ')],ndmin=2)
        np_out = np.append(np_out,np.array(data),axis=0)        

In [232]:
trans_mat = np.array(np_out[:4, :])
print(trans_mat)
for index, values in np.ndenumerate(np_out[:,0]):
    if(index[0] % 4 == 0):        
        trans_ind = index[0] 
        print(np_out[trans_ind:trans_ind+4, :])
        trans_mat = np.matmul(trans_mat,np_out[trans_ind:trans_ind+4, :])

trans_mat

[[-9.9224900e-01 -9.5700000e-03 -1.2389500e-01 -8.9394450e+00]
 [-4.7323000e-02  9.5100000e-01  3.0554700e-01 -2.0981476e+01]
 [ 1.1490000e-01  3.0904100e-01 -9.4408200e-01 -5.2502522e+01]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
[[-9.9224900e-01 -9.5700000e-03 -1.2389500e-01 -8.9394450e+00]
 [-4.7323000e-02  9.5100000e-01  3.0554700e-01 -2.0981476e+01]
 [ 1.1490000e-01  3.0904100e-01 -9.4408200e-01 -5.2502522e+01]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
[[ 1.        0.        0.       -0.324522]
 [ 0.        1.        0.       18.901092]
 [ 0.        0.        1.       51.476595]
 [ 0.        0.        0.        1.      ]]


array([[ 9.70775424e-01, -3.78938818e-02,  2.36977644e-01,
         1.78038316e+01],
       [ 3.70593767e-02,  9.99280432e-01,  7.97685723e-03,
        -3.72677202e+01],
       [-2.37109179e-01,  1.03835264e-03,  9.71481838e-01,
         3.96580357e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [238]:
def combine_trafomat_GM (filename):
    df = pd.read_csv(filename,delimiter='###',header=None,engine='python')[0]
    np_out = np.empty((0,4), float)
    for row in df:
        if row[0] != "#":
            if ',' in row:
                row = row.replace(',','.')
            data = np.array([float(x) for x in row.split(' ')],ndmin=2)
            np_out = np.append(np_out,np.array(data),axis=0)     
        trans_mat = np.array(np_out[:4, :])
    for index, values in np.ndenumerate(np_out[:,0]):
        if(index[0] % 4 == 0):        
            trans_ind = index[0] 
            trans_mat = np.matmul(trans_mat,np_out[trans_ind:trans_ind+4, :])

    return trans_mat

combine_trafomat_GM (filename)




array([[ 9.70775424e-01, -3.78938818e-02,  2.36977644e-01,
         1.78038316e+01],
       [ 3.70593767e-02,  9.99280432e-01,  7.97685723e-03,
        -3.72677202e+01],
       [-2.37109179e-01,  1.03835264e-03,  9.71481838e-01,
         3.96580357e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])